[installer] Move superuser check to the start of the script

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -25,6 +25,13 @@ OS_NAME="$PRETTY_NAME"
 # use xterm
 export TERM=xterm
 
+# check for super-user identity
+if [ "$(id -u)" != "0" ]; then
+    echo "  ERROR ! This script must be run as root or you must have sudo"
+    echo "  ERROR ! Try to execute 'sudo -i' and run again this command"
+    exit 1
+fi
+
 # Display libre installer header
 function print_header {
     cat <<-'BANNER'
@@ -66,11 +73,6 @@ function check_type {
 
 # Display information
 function prep_env {
-    if [ "$(id -u)" != "0" ]; then
-        echo "  ERROR ! This script must be run as root or you must have sudo"
-        echo "  ERROR ! Try to execute 'sudo -i' and run again this command"
-        exit 1
-    fi
     if [ ! -f $INSTALLER_BIN ]; then
         rm -rf $INSTALLER_BIN
         cp "$THIS_SCRIPT" $INSTALLER_BIN
