[installer] Add function prep_dir

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -71,22 +71,37 @@ function check_type {
     return 2
 }
 
+function prep_dir {
+    [ $# -eq 1 ] || {
+        return 1
+    }
+    local dir="$1"
+
+    mkdir -p "$dir" &> /dev/null || {
+        echo "  ERROR ! Unable to create $dir"
+        return 2
+    }
+    if [ ! -w "$dir" ]; then
+        echo "  ERROR ! $dir is not writable"
+        return 3
+    fi
+
+    return 0
+}
+
 # Display information
 function prep_env {
     if [ ! -f $INSTALLER_BIN ]; then
         rm -rf $INSTALLER_BIN
         cp "$THIS_SCRIPT" $INSTALLER_BIN
     fi
-    for d in $TMP_DEST $ANSIBLE_DEST; do
-        mkdir -p $d &> /dev/null || {
-            echo "  ERROR ! Unable to create $d"
-            exit 1
-        }
-        if [ ! -w $d ]; then
-            echo "  ERROR ! $d is not writable"
-            exit 1
-        fi
-    done
+
+    {
+        prep_dir $TMP_DEST     &&
+        prep_dir $ANSIBLE_DEST
+    }                          || exit 1
+
+    return 0
 }
 
 # installer update system
